---
# tasks file for vector
- include_tasks: 
    file: install.yml
    apply:
      tags: vector
  tags: vector

- include_tasks:
    file: configure.yml
    apply:
      tags: vector
  tags: vector
